server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: "auth-service"
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 734098679536-77u89g0lhplmtem7pgu0egkg8rq1e7ms.apps.googleusercontent.com
            client-secret: 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

openapi:
  service:
    title: auth-service doc
    version: 1.0.0
    url: http://localhost:8080

springdoc:
  api-docs:
    path: /auth-service/v3/api-docs
    enabled: true
  swagger-ui:
    path: /auth-service/swagger-ui.html
    enabled: true