server:
  port: 8082

spring:
  application:
    name: food-service
  datasource:
    url: jdbc:postgresql://localhost:5432/food_db
    username: suneclipse
    password: suneclipse
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres
      mode: always
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: 'true'
  flyway:
    enabled: true
    locations: classpath:db/migration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

openapi:
  service:
    title: food-service doc
    version: 1.0.0
    url: http://localhost:8080

springdoc:
  api-docs:
    path: /food-service/v3/api-docs
  swagger-ui:
    path: /food-service/swagger-ui.html

logging:
  level:
    org:
      springframework:
        jpa: DEBUG
